name: CustomJoinEvents
version: 1.3.2
main: com.imjona.customjoinevents.CustomJoinEvents
api-version: 1.13
author: _ImJona
description: Multiple event plugin when a player enters the server
softdepend:
  - PlaceholderAPI